// Generates server/src/generated/embeddedAssets.ts from the built web/dist.
//
// Bun's `bun build --compile` embeds any file imported with `{ type: "file" }`
// into the executable; the imported value is a path readable at runtime via
// `Bun.file()`. Since Vite emits hash-named files we can't hardcode, we scan
// web/dist and emit one import + route-map entry per file.

import { promises as fs } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const distDir = path.join(root, "web", "dist");
const outDir = path.join(root, "server", "src", "generated");
const outFile = path.join(outDir, "embeddedAssets.ts");

async function walk(dir) {
  const entries = await fs.readdir(dir, { withFileTypes: true });
  const files = [];
  for (const e of entries) {
    const full = path.join(dir, e.name);
    if (e.isDirectory()) files.push(...(await walk(full)));
    else files.push(full);
  }
  return files;
}

async function main() {
  try {
    await fs.access(distDir);
  } catch {
    console.error(`[embed-web] ${distDir} not found — run the web build first.`);
    process.exit(1);
  }

  const files = await walk(distDir);
  files.sort();

  const imports = [];
  const routes = [];
  files.forEach((abs, i) => {
    // Route: path under dist, POSIX-style, leading slash.
    const route = "/" + path.relative(distDir, abs).split(path.sep).join("/");
    // Import specifier: relative from the generated file, POSIX-style.
    let spec = path.relative(outDir, abs).split(path.sep).join("/");
    if (!spec.startsWith(".")) spec = "./" + spec;
    imports.push(`import f${i} from "${spec}" with { type: "file" };`);
    routes.push(`  ${JSON.stringify(route)}: f${i},`);
  });

  const body = `// AUTO-GENERATED by scripts/embed-web.mjs — do not edit.
// Embeds the built web UI (web/dist) into the Bun single-file executable.
${imports.join("\n")}

export const ASSETS: Record<string, string> = {
${routes.join("\n")}
};
`;

  await fs.mkdir(outDir, { recursive: true });
  await fs.writeFile(outFile, body, "utf8");
  console.log(`[embed-web] wrote ${files.length} assets to ${path.relative(root, outFile)}`);
}

main().catch((e) => {
  console.error("[embed-web]", e);
  process.exit(1);
});
